# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
#Test
name: Calculator run tests

on:
  push:
    branches: [ devBranch ]
  pull_request:
    branches: [ devBranch ]
    

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    
  #build:

    #runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
    - name: Run tests with Maven
      run: mvn -B test --file pom.xml
    #- name: Build with Maven
      #run: mvn -B package --file pom.xml
    #- name: Maven Package
      #run: mvn -B clean package -DskipTests
    #- name: Run tests with Maven
      #run: mvn -B test --file pom.xml
    #- name: Maven Verify
      #run: mvn -B clean verify
